### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by mrpep** [google/fiddle#164]
I am trying to run [this colab](https://colab.research.google.com/github/google/fiddle/blob/main/fiddle/examples/colabs/fiddle_tutorial_with_flax.ipynb?authuser=1#scrollTo=33zel0HX-u0M) from the documentation but importing fails when running the first cell.

```Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting fiddle
  Downloading fiddle-0.2.2-py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 7.6 MB/s 
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.7/dist-packages (from fiddle) (4.1.1)
Collecting libcst
  Downloading libcst-0.4.7-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.7 MB)
     |████████████████████████████████| 2.7 MB 54.7 MB/s 
Requirement already satisfied: pyyaml>=5.2 in /usr/local/lib/python3.7/dist-packages (from libcst->fiddle) (6.0)
Collecting typing-inspect>=0.4.0
  Downloading typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)
Collecting mypy-extensions>=0.3.0
  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)
Installing collected packages: mypy-extensions, typing-inspect, libcst, fiddle
Successfully installed fiddle-0.2.2 libcst-0.4.7 mypy-extensions-0.4.3 typing-inspect-0.8.0
Traceback (most recent call last):

  File "/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File ["<ipython-input-1-ba42286d1387>"](https://localhost:8080/#), line 3, in <module>
    import fiddle as fdl

  File "/usr/local/lib/python3.7/dist-packages/fiddle/__init__.py", line 18, in <module>
    from fiddle.building import build

  File "/usr/local/lib/python3.7/dist-packages/fiddle/building.py", line 22, in <module>
    from fiddle import config

  File "/usr/local/lib/python3.7/dist-packages/fiddle/config.py", line 86
    def __init__(self, fn_or_cls: Union['Buildable', TypeOrCallableProducingT], /,
                                                                                ^
SyntaxError: invalid syntax

**Comment by wookayin** [comment]
[Positional-only arguments](https://peps.python.org/pep-0570/) are a feature in python 3.8 or higher. [Fiddle is compatible with python 3.8+ only](https://github.com/google/fiddle/blob/main/setup.py#L80).
